{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 112154,
          "sha512": "20f6bda507e3a61979d549faf535fbf413d08a863ddad1e9fc611b50677d8b894232444f98153d713cee7c15e81da6ccdaf1c90a872a424044c7460eaea0982d",
          "sha256": "bc529ef582db2abbb5bfb5d8a0b13f2ea2470f50af6efa0643decb9d60175092",
          "sha1": "0c702ccc08fab94a57c5a150beb07c65c4d43a21",
          "md5": "61bab84ec9cc4797688d42296e63b26d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 112154,
          "sha512": "20f6bda507e3a61979d549faf535fbf413d08a863ddad1e9fc611b50677d8b894232444f98153d713cee7c15e81da6ccdaf1c90a872a424044c7460eaea0982d",
          "sha256": "bc529ef582db2abbb5bfb5d8a0b13f2ea2470f50af6efa0643decb9d60175092",
          "sha1": "0c702ccc08fab94a57c5a150beb07c65c4d43a21",
          "md5": "61bab84ec9cc4797688d42296e63b26d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0-sources.jar",
          "url": "shared_preferences_android_release-1.0-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0-javadoc.jar",
          "url": "shared_preferences_android_release-1.0-javadoc.jar",
          "size": 358386,
          "sha512": "93a247a12e29e5188b7680773ad4c5ccd1c5f07e61ac5a041baed368b61c280f0c391b3ac7a5e922809c9a6e99a8110b5e4420d0c6f80d808cf7f98828d7fcc7",
          "sha256": "677fd94f1f05b574730db8d25a298566aea701f4207abf5e4780873302da4455",
          "sha1": "6451b5003a952f9b33ec75136150a20176ddc8f7",
          "md5": "560c3d800638f6aa1168b9631e13e002"
        }
      ]
    }
  ]
}
