{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flutter.stripe",
    "module": "stripe_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "stripe_android_debug-1.0.aar",
          "url": "stripe_android_debug-1.0.aar",
          "size": 440506,
          "sha512": "c48f36de7503093284b00f1f21b999c5883b22b402295be2701c17cf6dd9be1b36fa97397174034628421470c240521a9b2ad6e5f82a952e43d47b14e9d6a760",
          "sha256": "e369286f308367fc36df116d9cfb42b2a5f8900ea4c5e024f2f723842deff663",
          "sha1": "d36e52e2596a0e0f75f32cf6e160de913c3edc7d",
          "md5": "1514db4165b1f220e2062132c345adf0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "21.6.+"
          }
        },
        {
          "group": "com.stripe",
          "module": "financial-connections",
          "version": {
            "requires": "21.6.+"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "stripe_android_debug-1.0.aar",
          "url": "stripe_android_debug-1.0.aar",
          "size": 440506,
          "sha512": "c48f36de7503093284b00f1f21b999c5883b22b402295be2701c17cf6dd9be1b36fa97397174034628421470c240521a9b2ad6e5f82a952e43d47b14e9d6a760",
          "sha256": "e369286f308367fc36df116d9cfb42b2a5f8900ea4c5e024f2f723842deff663",
          "sha1": "d36e52e2596a0e0f75f32cf6e160de913c3edc7d",
          "md5": "1514db4165b1f220e2062132c345adf0"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stripe_android_debug-1.0-sources.jar",
          "url": "stripe_android_debug-1.0-sources.jar",
          "size": 112309,
          "sha512": "c431962aff0cfa7d2fbe8e6a5592169acbfc0a2304d5623631df1f54dfcb4a0cf7a0d3012cf1c3497a72bf8a86fb4476c78b553d54caae138a0eb75ca3fb399c",
          "sha256": "edb05a97043ea033612dceea8bfe0655af0db27809f21d7ee25fbd1185de89e7",
          "sha1": "56ff9f3145b6a2941ee258812b50f60e07278ba6",
          "md5": "6751746175b607818ad1d35289bd0916"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stripe_android_debug-1.0-javadoc.jar",
          "url": "stripe_android_debug-1.0-javadoc.jar",
          "size": 896351,
          "sha512": "6342e1598401aece2d31653008614cb55ce41e53b79b94672bd1df0f9baca170f93fece041302437584ce408cca396d793394189b5beef478964965a5f8ee8ff",
          "sha256": "307f0ee05bff2965e287f561f5f03606e48c311b748b17bec2e92c25c2f23885",
          "sha1": "1cb4f3a5559d9388b2d82bf9ce1570cd45ccb4a8",
          "md5": "5f0bc592dae19bc1b2fb5cc11a3990a5"
        }
      ]
    }
  ]
}
