// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.zetexa.app_sdk.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BrandMessagingPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class BrandEnvironment(val raw: Int) {
  DEV(0),
  PROD(1),
  QA(2),
  STG(3);

  companion object {
    fun ofRaw(raw: Int): BrandEnvironment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BrandColorConfig (
  val primary: String,
  val secondary: String,
  val tertiary: String,
  val success: String,
  val error: String,
  val warning: String,
  val background: String,
  val secondaryBackground: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrandColorConfig {
      val primary = pigeonVar_list[0] as String
      val secondary = pigeonVar_list[1] as String
      val tertiary = pigeonVar_list[2] as String
      val success = pigeonVar_list[3] as String
      val error = pigeonVar_list[4] as String
      val warning = pigeonVar_list[5] as String
      val background = pigeonVar_list[6] as String
      val secondaryBackground = pigeonVar_list[7] as String
      return BrandColorConfig(primary, secondary, tertiary, success, error, warning, background, secondaryBackground)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      primary,
      secondary,
      tertiary,
      success,
      error,
      warning,
      background,
      secondaryBackground,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrandColorConfig
    return BrandMessagingPigeonUtils.deepEquals(this.primary, other.primary) && BrandMessagingPigeonUtils.deepEquals(this.secondary, other.secondary) && BrandMessagingPigeonUtils.deepEquals(this.tertiary, other.tertiary) && BrandMessagingPigeonUtils.deepEquals(this.success, other.success) && BrandMessagingPigeonUtils.deepEquals(this.error, other.error) && BrandMessagingPigeonUtils.deepEquals(this.warning, other.warning) && BrandMessagingPigeonUtils.deepEquals(this.background, other.background) && BrandMessagingPigeonUtils.deepEquals(this.secondaryBackground, other.secondaryBackground)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.primary)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.secondary)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.tertiary)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.success)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.error)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.warning)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.background)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.secondaryBackground)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BrandTypographyConfig (
  val headingFontFamily: String,
  val bodyFontFamily: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrandTypographyConfig {
      val headingFontFamily = pigeonVar_list[0] as String
      val bodyFontFamily = pigeonVar_list[1] as String
      return BrandTypographyConfig(headingFontFamily, bodyFontFamily)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      headingFontFamily,
      bodyFontFamily,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrandTypographyConfig
    return BrandMessagingPigeonUtils.deepEquals(this.headingFontFamily, other.headingFontFamily) && BrandMessagingPigeonUtils.deepEquals(this.bodyFontFamily, other.bodyFontFamily)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.headingFontFamily)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.bodyFontFamily)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BrandThemeConfig (
  val colors: BrandColorConfig,
  val typography: BrandTypographyConfig
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrandThemeConfig {
      val colors = pigeonVar_list[0] as BrandColorConfig
      val typography = pigeonVar_list[1] as BrandTypographyConfig
      return BrandThemeConfig(colors, typography)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      colors,
      typography,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrandThemeConfig
    return BrandMessagingPigeonUtils.deepEquals(this.colors, other.colors) && BrandMessagingPigeonUtils.deepEquals(this.typography, other.typography)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.colors)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.typography)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BrandConfig (
  val resellerId: String,
  val resellerEmail: String,
  val resellerName: String,
  val preferredCurrency: String,
  val environment: BrandEnvironment,
  val theme: BrandThemeConfig,
  /** When set, the authentication flow pre-fills this email (from the host app). */
  val prefillAuthEmail: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrandConfig {
      val resellerId = pigeonVar_list[0] as String
      val resellerEmail = pigeonVar_list[1] as String
      val resellerName = pigeonVar_list[2] as String
      val preferredCurrency = pigeonVar_list[3] as String
      val environment = pigeonVar_list[4] as BrandEnvironment
      val theme = pigeonVar_list[5] as BrandThemeConfig
      val prefillAuthEmail = pigeonVar_list[6] as String?
      return BrandConfig(resellerId, resellerEmail, resellerName, preferredCurrency, environment, theme, prefillAuthEmail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      resellerId,
      resellerEmail,
      resellerName,
      preferredCurrency,
      environment,
      theme,
      prefillAuthEmail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrandConfig
    return BrandMessagingPigeonUtils.deepEquals(this.resellerId, other.resellerId) && BrandMessagingPigeonUtils.deepEquals(this.resellerEmail, other.resellerEmail) && BrandMessagingPigeonUtils.deepEquals(this.resellerName, other.resellerName) && BrandMessagingPigeonUtils.deepEquals(this.preferredCurrency, other.preferredCurrency) && BrandMessagingPigeonUtils.deepEquals(this.environment, other.environment) && BrandMessagingPigeonUtils.deepEquals(this.theme, other.theme) && BrandMessagingPigeonUtils.deepEquals(this.prefillAuthEmail, other.prefillAuthEmail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.resellerId)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.resellerEmail)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.resellerName)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.preferredCurrency)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.environment)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.theme)
    result = 31 * result + BrandMessagingPigeonUtils.deepHash(this.prefillAuthEmail)
    return result
  }
}
private open class BrandMessagingPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BrandEnvironment.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrandColorConfig.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrandTypographyConfig.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrandThemeConfig.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrandConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BrandEnvironment -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BrandColorConfig -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BrandTypographyConfig -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is BrandThemeConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is BrandConfig -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeBrandConfigApi {
  fun getInitialBrandTheme(): BrandConfig

  companion object {
    /** The codec used by NativeBrandConfigApi. */
    val codec: MessageCodec<Any?> by lazy {
      BrandMessagingPigeonCodec()
    }
    /** Sets up an instance of `NativeBrandConfigApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeBrandConfigApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.app_sdk.NativeBrandConfigApi.getInitialBrandTheme$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getInitialBrandTheme())
            } catch (exception: Throwable) {
              BrandMessagingPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FlutterBrandConfigApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterBrandConfigApi. */
    val codec: MessageCodec<Any?> by lazy {
      BrandMessagingPigeonCodec()
    }
  }
  fun onBrandThemeUpdated(brandConfigArg: BrandConfig, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.app_sdk.FlutterBrandConfigApi.onBrandThemeUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(brandConfigArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BrandMessagingPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
