// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.zetexa.app_sdk.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CheckoutMessagingPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/** Generated class from Pigeon that represents data sent in messages. */
data class CheckoutAddress (
  val firstName: String,
  val lastName: String,
  val street1: String,
  val city: String,
  val state: String,
  val countryIso2: String,
  val postalCode: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CheckoutAddress {
      val firstName = pigeonVar_list[0] as String
      val lastName = pigeonVar_list[1] as String
      val street1 = pigeonVar_list[2] as String
      val city = pigeonVar_list[3] as String
      val state = pigeonVar_list[4] as String
      val countryIso2 = pigeonVar_list[5] as String
      val postalCode = pigeonVar_list[6] as String
      return CheckoutAddress(firstName, lastName, street1, city, state, countryIso2, postalCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      firstName,
      lastName,
      street1,
      city,
      state,
      countryIso2,
      postalCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CheckoutAddress
    return CheckoutMessagingPigeonUtils.deepEquals(this.firstName, other.firstName) && CheckoutMessagingPigeonUtils.deepEquals(this.lastName, other.lastName) && CheckoutMessagingPigeonUtils.deepEquals(this.street1, other.street1) && CheckoutMessagingPigeonUtils.deepEquals(this.city, other.city) && CheckoutMessagingPigeonUtils.deepEquals(this.state, other.state) && CheckoutMessagingPigeonUtils.deepEquals(this.countryIso2, other.countryIso2) && CheckoutMessagingPigeonUtils.deepEquals(this.postalCode, other.postalCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.firstName)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.lastName)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.street1)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.city)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.state)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.countryIso2)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.postalCode)
    return result
  }
}

/**
 * Billing/contact hints from the native host (prefill only).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeCheckoutPrefillProfile (
  val nativePrefillFirstName: String,
  val nativePrefillLastName: String,
  val nativePrefillEmail: String,
  val nativePrefillPhone: String,
  val nativePrefillNationalityIso2: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCheckoutPrefillProfile {
      val nativePrefillFirstName = pigeonVar_list[0] as String
      val nativePrefillLastName = pigeonVar_list[1] as String
      val nativePrefillEmail = pigeonVar_list[2] as String
      val nativePrefillPhone = pigeonVar_list[3] as String
      val nativePrefillNationalityIso2 = pigeonVar_list[4] as String
      return NativeCheckoutPrefillProfile(nativePrefillFirstName, nativePrefillLastName, nativePrefillEmail, nativePrefillPhone, nativePrefillNationalityIso2)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nativePrefillFirstName,
      nativePrefillLastName,
      nativePrefillEmail,
      nativePrefillPhone,
      nativePrefillNationalityIso2,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCheckoutPrefillProfile
    return CheckoutMessagingPigeonUtils.deepEquals(this.nativePrefillFirstName, other.nativePrefillFirstName) && CheckoutMessagingPigeonUtils.deepEquals(this.nativePrefillLastName, other.nativePrefillLastName) && CheckoutMessagingPigeonUtils.deepEquals(this.nativePrefillEmail, other.nativePrefillEmail) && CheckoutMessagingPigeonUtils.deepEquals(this.nativePrefillPhone, other.nativePrefillPhone) && CheckoutMessagingPigeonUtils.deepEquals(this.nativePrefillNationalityIso2, other.nativePrefillNationalityIso2)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativePrefillFirstName)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativePrefillLastName)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativePrefillEmail)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativePrefillPhone)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativePrefillNationalityIso2)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeHostCheckoutContextMessage (
  /** Host-side session flag — not a Flutter auth token. */
  val nativeHostUserSignedIn: Boolean,
  val nativePrefillProfile: NativeCheckoutPrefillProfile,
  val nativeDefaultBillingAddress: CheckoutAddress? = null,
  val nativeDefaultShippingAddress: CheckoutAddress? = null,
  val nativeHostSessionRef: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHostCheckoutContextMessage {
      val nativeHostUserSignedIn = pigeonVar_list[0] as Boolean
      val nativePrefillProfile = pigeonVar_list[1] as NativeCheckoutPrefillProfile
      val nativeDefaultBillingAddress = pigeonVar_list[2] as CheckoutAddress?
      val nativeDefaultShippingAddress = pigeonVar_list[3] as CheckoutAddress?
      val nativeHostSessionRef = pigeonVar_list[4] as String?
      return NativeHostCheckoutContextMessage(nativeHostUserSignedIn, nativePrefillProfile, nativeDefaultBillingAddress, nativeDefaultShippingAddress, nativeHostSessionRef)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nativeHostUserSignedIn,
      nativePrefillProfile,
      nativeDefaultBillingAddress,
      nativeDefaultShippingAddress,
      nativeHostSessionRef,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeHostCheckoutContextMessage
    return CheckoutMessagingPigeonUtils.deepEquals(this.nativeHostUserSignedIn, other.nativeHostUserSignedIn) && CheckoutMessagingPigeonUtils.deepEquals(this.nativePrefillProfile, other.nativePrefillProfile) && CheckoutMessagingPigeonUtils.deepEquals(this.nativeDefaultBillingAddress, other.nativeDefaultBillingAddress) && CheckoutMessagingPigeonUtils.deepEquals(this.nativeDefaultShippingAddress, other.nativeDefaultShippingAddress) && CheckoutMessagingPigeonUtils.deepEquals(this.nativeHostSessionRef, other.nativeHostSessionRef)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativeHostUserSignedIn)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativePrefillProfile)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativeDefaultBillingAddress)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativeDefaultShippingAddress)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.nativeHostSessionRef)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaymentResultMessage (
  val orderId: String,
  val currency: String,
  val amount: Double,
  val kycPending: Boolean,
  val hasEsimData: Boolean,
  val suggestedRoute: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PaymentResultMessage {
      val orderId = pigeonVar_list[0] as String
      val currency = pigeonVar_list[1] as String
      val amount = pigeonVar_list[2] as Double
      val kycPending = pigeonVar_list[3] as Boolean
      val hasEsimData = pigeonVar_list[4] as Boolean
      val suggestedRoute = pigeonVar_list[5] as String
      return PaymentResultMessage(orderId, currency, amount, kycPending, hasEsimData, suggestedRoute)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      orderId,
      currency,
      amount,
      kycPending,
      hasEsimData,
      suggestedRoute,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PaymentResultMessage
    return CheckoutMessagingPigeonUtils.deepEquals(this.orderId, other.orderId) && CheckoutMessagingPigeonUtils.deepEquals(this.currency, other.currency) && CheckoutMessagingPigeonUtils.deepEquals(this.amount, other.amount) && CheckoutMessagingPigeonUtils.deepEquals(this.kycPending, other.kycPending) && CheckoutMessagingPigeonUtils.deepEquals(this.hasEsimData, other.hasEsimData) && CheckoutMessagingPigeonUtils.deepEquals(this.suggestedRoute, other.suggestedRoute)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.orderId)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.currency)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.amount)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.kycPending)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.hasEsimData)
    result = 31 * result + CheckoutMessagingPigeonUtils.deepHash(this.suggestedRoute)
    return result
  }
}
private open class CheckoutMessagingPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CheckoutAddress.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCheckoutPrefillProfile.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHostCheckoutContextMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentResultMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CheckoutAddress -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeCheckoutPrefillProfile -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeHostCheckoutContextMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PaymentResultMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HostToFlutterCheckoutApi {
  fun getNativeHostCheckoutContext(): NativeHostCheckoutContextMessage

  companion object {
    /** The codec used by HostToFlutterCheckoutApi. */
    val codec: MessageCodec<Any?> by lazy {
      CheckoutMessagingPigeonCodec()
    }
    /** Sets up an instance of `HostToFlutterCheckoutApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HostToFlutterCheckoutApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.app_sdk.HostToFlutterCheckoutApi.getNativeHostCheckoutContext$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNativeHostCheckoutContext())
            } catch (exception: Throwable) {
              CheckoutMessagingPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FlutterToHostCheckoutApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterToHostCheckoutApi. */
    val codec: MessageCodec<Any?> by lazy {
      CheckoutMessagingPigeonCodec()
    }
  }
  fun onPaymentSuccess(payloadArg: PaymentResultMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.app_sdk.FlutterToHostCheckoutApi.onPaymentSuccess$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(payloadArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CheckoutMessagingPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPaymentFailure(payloadJsonArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.app_sdk.FlutterToHostCheckoutApi.onPaymentFailure$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(payloadJsonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CheckoutMessagingPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPostPurchaseNavigationSuggested(payloadJsonArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.app_sdk.FlutterToHostCheckoutApi.onPostPurchaseNavigationSuggested$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(payloadJsonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CheckoutMessagingPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
