{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.dart_lang.jni",
    "module": "jni_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "jni_release-1.0.aar",
          "url": "jni_release-1.0.aar",
          "size": 104420,
          "sha512": "2ef80a6b1bc3e75c18393db89a98ad7c6a58a7b4e739693da43cb6e3b990248fb0bb44966756cdcb93d86d2f18b4b32565300981e1691720d5d0c3fea3344379",
          "sha256": "0d547de14bf181ffa60ce0a028c630c9f5e03f28de47dc9487d2cff94ff15346",
          "sha1": "fed46a7d5be8f609d00d0d7afd36436d9f1bbb26",
          "md5": "e4d5a10a1dc9fda70a2e4db03c3c1f26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "jni_release-1.0.aar",
          "url": "jni_release-1.0.aar",
          "size": 104420,
          "sha512": "2ef80a6b1bc3e75c18393db89a98ad7c6a58a7b4e739693da43cb6e3b990248fb0bb44966756cdcb93d86d2f18b4b32565300981e1691720d5d0c3fea3344379",
          "sha256": "0d547de14bf181ffa60ce0a028c630c9f5e03f28de47dc9487d2cff94ff15346",
          "sha1": "fed46a7d5be8f609d00d0d7afd36436d9f1bbb26",
          "md5": "e4d5a10a1dc9fda70a2e4db03c3c1f26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_release-1.0-sources.jar",
          "url": "jni_release-1.0-sources.jar",
          "size": 5459,
          "sha512": "61c8d0b11708383673e2d967abe5948df4f9f1c20f77852bfc8e4da61a83bb5c2e7561a02692dc183a64b4f842555d66ebd142d02b6295313fcda91f9e8e0c15",
          "sha256": "0762cdfe1e25701b53f0e55fde69135e74f25328f4b1c60e4778701833bfab6e",
          "sha1": "09a60f323f1b590e7921cd33327514fe4d916cb1",
          "md5": "3cf8aa129d418b4388b02cea9ff9819b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_release-1.0-javadoc.jar",
          "url": "jni_release-1.0-javadoc.jar",
          "size": 283174,
          "sha512": "979a88196ffbc31f7fa058c7e7c61413ceb7a541f97aea9800795c13a793430f8cf9e2f158ada4af3e96d4f8771fa9424f8fe8825c7960b02e1107f42f8c652e",
          "sha256": "401e919d42f634c413f998892929d32e3da0e87497baa05e93e591e4282c9509",
          "sha1": "227e24a04e289a637d787206c63b85d7b98ecd15",
          "md5": "77c128fb107b1e179e87f0882d957777"
        }
      ]
    }
  ]
}
